### ISSUE TITLE
Traditional behaviour for footnotes

### ISSUE THREAD

**Issue by asbrwl** [WingLim/hugo-tania#10]

**Comment by asbrwl** [comment]
Is it possible to render the footnotes at the bottom of the page as is traditional, rather than floating. 
I find its difficult to use on mobile, as the footnote comes in the middle of the text.

**Comment by WingLim** [comment]
This a feature of the theme.
How about add a switch in theme config to disable it.

**Comment by WingLim** [comment]
You can disable the footnotes now, with #11 .
