### ISSUE TITLE
How to enable Search feature

### ISSUE THREAD

**Issue by hellodit** [WingLim/hugo-tania#12]
Hii,
How can I enable the search feature on these themes? 
I just want to add a search feature so my visitor can easily search article on my website using keyword, 
additionally, I want to add some tags above the search bar. 

Thanks!

**Comment by WingLim** [comment]
This theme didn't have search feature yet.
But I can add a search input in article page.
Like this(from https://www.taniarascia.com/blog):
![image](https://user-images.githubusercontent.com/6434137/121773232-13fc1380-cbad-11eb-978c-015ed5fe26be.png)
For index, it should be a show page which means it show the latest articles you write and the project you have done.

**Comment by hellodit** [comment]
It's nice to have a search feature on the articles page, how can I implement it on my own? 

I think a search feature like this will be nice, so user have option to choose tags or search 
![search feature](https://user-images.githubusercontent.com/32544683/121773448-38082680-cba6-11eb-9c15-dffa44b27430.PNG)

**Comment by WingLim** [comment]
Most developers will use flex search.js, fuse.js or something like them to implement it.

Can you send me the url of your screenshot?

I will add it now.

**Comment by hellodit** [comment]
here is the URL you request 

https://teguh.co/blog

**Comment by WingLim** [comment]
Take a look at netlify preview: https://deploy-preview-13--hugo-tania.netlify.app/articles/

And the tag filter/category filter in the url you gave, it's a little hard to implement in hugo.

It's easy to do like:
- click only one tag/category
- show the related articles

It's hard to do like:
- selected multi tag/category
- show the related articles

I can implement it in easy way, and don't have idea to do hard way yet.

**Comment by hellodit** [comment]
I think `click only one tag/category` is enough, what do you think?

**Comment by WingLim** [comment]
Ok, will do it tomorrow.

**Comment by hellodit** [comment]
Thank you so much winglim!

**Comment by WingLim** [comment]
Hi, there.
I have implement the filter with categories and tags.
Which is the hard way I mention above.

We can select multi categories and tags, and type in search input like title and contents, for searching more details.

Still the same preview url: https://deploy-preview-13--hugo-tania.netlify.app/articles/

But there is a question I need help.
Now I put the categories and tags in a same div, it's hard to distinguish.

I have serval ideas about it.
1. add `#` for tags
2. split out two div, one for categories, the other for tags

Can you give me some advises?

**Comment by hellodit** [comment]
I just know that Hugo has categories and tags. 
How about the filter just for categories?
Then show only 5 most used categories

**Comment by WingLim** [comment]
Do you mean most used is order categories by date?

**Comment by hellodit** [comment]
Yes. I just think if someone has many categories to show it will break the user experience

**Comment by WingLim** [comment]
Oh, I found that categories is default order by date.
I just need to add count limit.

**Comment by WingLim** [comment]
The feature has been implement.
 If there are any problems, reopen this issue or create a new issue to report problem
