### ISSUE TITLE
Ignoring resources folder change 

### ISSUE THREAD

**Issue by hellodit** [WingLim/hugo-tania#18]
Based on this [discussion](https://discourse.gohugo.io/t/should-i-add-resources-to-gitignore/20064), I recommend adding `resources` folder to .gitignore

**Comment by WingLim** [comment]
Because I am using `sass` to write style.
The style will only gernerate with `hugo extended` binary version.
`resources` is for user who use normal `hugo` binary.

**Comment by hellodit** [comment]
So you would not ignore this folder?

**Comment by WingLim** [comment]
Yes, this is using for compatibility.
And the `resources` only have style file in this theme.

**Comment by hellodit** [comment]
Oke thanks, I understand
