### ISSUE TITLE
Alphabetise the tags output

### ISSUE THREAD

**Issue by asbrwl** [WingLim/hugo-tania#20]
For the article tags output in the template here

`                        <div class="tags">
                            {{ range (.GetTerms "tags") }}
                            <a href="{{ .RelPermalink }}">{{ .LinkTitle }}</a>
                            {{ end }}
                        </div>`

Is it possible to alphabetise the output?

**Comment by WingLim** [comment]
Yes, use [`upper`](https://gohugo.io/functions/upper/)

```
<div class="tags"> 
{{ range (.GetTerms "tags") }} 
<a href="{{ .RelPermalink }}">{{ upper .LinkTitle }}</a> 
{{ end }} 
</div>
```

**Comment by asbrwl** [comment]
Sorry I wasnt clear in my question.
So in the fmrontmtter I have my tags as 

`tags: [ 'book', 'apple', 'fruit' 'cucumber']`

Now when this gets outputted on the page, it gets outputted as 

book apple fruit cucumber

I would like it to be 

apple book cucumber fruit

i.e sorted in ascending order.

**Comment by WingLim** [comment]
Oh, it's my fault. I didn't read your question carefully.

You can use function [`sort`](https://gohugo.io/functions/sort/) to do this.

Here is the example:
```html
<div class="tags">
{{ range sort (.GetTerms "tags") "LinkTitle" }}
<a href="{{ .RelPermalink }}">{{ .LinkTitle }}</a>
{{ end }}
</div>
```

**Comment by asbrwl** [comment]
Thanks for the guidance.
