### ISSUE TITLE
Broken image rendering

### ISSUE THREAD

**Issue by wheleph** [WingLim/hugo-tania#28]
After upgrading to the latest version of the theme (https://gitlab.com/wheleph/wheleph.gitlab.io/-/commit/974e14a48325fda0baa080c082321dfe38e0ad2b), images in one of my posts can no longer be rendered:

```
Error: Error building site: "/builds/wheleph/wheleph.gitlab.io/content/posts/2015-06-27-on-rabbitmq-automatic-ack-and-reliable-message-processing/index.md:4:125": execute of template failed: template: _default/_markup/render-image.html:4:125: executing "_default/_markup/render-image.html" at <imageConfig (printf "static/%s" .Destination)>: error calling imageConfig: open /builds/wheleph/wheleph.gitlab.io/static/rabbitmq_auto_ack.png: no such file or directory
```

Here's the relevant markdown piece:

```
![Management plugin screenshot: auto ack](rabbitmq_auto_ack.png)
```

Here's the CI build: https://gitlab.com/wheleph/wheleph.gitlab.io/-/jobs/1433218665

Am I missing something?

**Comment by deovaliandro** [comment]
Save all images in /static folder..

**Comment by WingLim** [comment]
With 08a430a, hugo will auto search image in post folder or `static` folder.

**Comment by wheleph** [comment]
Thank you! With the fix, I'm able to keep images in my posts directories. Just like I did before.

**Comment by hurutoriya** [comment]
@WingLim Hello, nice to meet you.
I love your hugo theme, it is a pretty simple and beautiful design 😄 

Regarding this updates
> With 08a430a, hugo will auto search image in post folder or static folder.

It supported images in post folder but still put the error when I update the `hugo-tania` theme.


```
diff --git a/themes/hugo-tania b/themes/hugo-tania
index 0a54b432..99acf147 160000
--- a/themes/hugo-tania
+++ b/themes/hugo-tania
@@ -1 +1 @@
-Subproject commit 0a54b432f9e7318e202760dcd400ab9cefc17882
+Subproject commit 99acf147092a853126c178ffdfaa481ae738d180

```

```
Start building sites … 
hugo v0.89.0+extended darwin/amd64 BuildDate=unknown
Error: Error building site: "/Users/hurutoriya/code/hurutoriya.github.io/themes/hugo-tania/layouts/_default/_markup/render-image.html:13:15": execute of template failed: template: _default/_markup/render-image.html:13:15: executing "_default/_markup/render-image.html" at <imageConfig (printf "static/%s" (.Destination | safeURL))>: error calling imageConfig: open /Users/hurutoriya/code/hurutoriya.github.io/static/posts/2017-11-13/images/1.gif: no such file or directory
```
error messages say broken the post directory images rendering images.
Actual file structure is here.

I guess  `_markup/render-image.html` build as under `/static` path even under `posts` directory but it seems failed?
Sorry I don't have a knowledge about hugo theme but I would like to share it 🙇 .

https://github.com/hurutoriya/hurutoriya.github.io/tree/source/content/posts/2017-11-13
