### ISSUE TITLE
Hugo theme introduction page link error

### ISSUE THREAD

**Issue by zincnode** [WingLim/hugo-tania#4]
Hello there,
I just saw the [Hugo introduction page](https://themes.gohugo.io/hugo-tania/) of this theme, there is a link pointing to the wrong.

![0001](https://user-images.githubusercontent.com/37936328/109934683-c1869d80-7d07-11eb-87da-9f5ec1334623.PNG)

Currently "Homepage" points to ***hugo-tanhia.netlify.app***, I think it should point to the [Github repository](https://github.com/WingLim/hugo-tania).

**Comment by WingLim** [comment]
Sorry for that, it is already fix.
