### ISSUE TITLE
Utterances as comments provider not rendering correctly

### ISSUE THREAD

**Issue by marcelherd** [WingLim/hugo-tania#47]
Hi,

when using Utteranc.es as comment provider, it did not render correctly for me. In my case this was caused by [this line](https://github.com/WingLim/hugo-tania/blob/1ec0b265c10813fe602d9a15aeaef5ddee3f8c3e/layouts/partials/comments/provider/utterances.html#L34). The property `document.documentElement.dataset.scheme` is undefined for me, I fixed it by changing it to `document.documentElement.dataset.userColorScheme`.

**Comment by WingLim** [comment]
Sorry for that, will fix it soon.
And thanks for your feedback.
