### ISSUE TITLE
你好，请问首页内容过多分页的问题

### ISSUE THREAD

**Issue by mtdsj** [WingLim/hugo-tania#6]
你好，我的网站内容多，想在首页实现分页功能。按照以往成功的经验，在index中加入{{ partial "pagination.html" . }}
在partials加入pagination.html。
虽然首页可以正确显示分页和页码，但是点击后，始终只显示第一页。请问这个是什么原因？怎么解决？
谢谢

**Comment by WingLim** [comment]
因为之前是在`index.html`通过手动设置参数来限制首页文章数量，没有使用 Hugo 官方的 `.Paginate`。
没加分页是因为文章块后还会项目块，没考虑好分页块该加在哪里，所以就没加。
现在换成 `.Paginate` 来限制首页文章数量，现在你在`index.html`中添加`{{ partial "pagination.html" . }}`应该可以正常分页了。

**Comment by mtdsj** [comment]
非常感谢，问题解决了。
我的新问题是：如果设置Paginate为10，点击某个标签后，即使相同标签的文章有100篇，也会显示 10  posts found.点击下一页也可以看到更多。
也就是说，这个标签数量统计不准。但是如果同一个标签的文章数量小于Paginate的数值，就可以正常显示。
相关：<span class="count">{{ len $pages }}</span> posts found.
---
另外，主题exampleSite/config.yaml的写法，如果复制到我的theme.toml文件中是无效的。比如paginate: 6，修改成paginate = "100"才行。

**Comment by WingLim** [comment]
toml和yaml格式上有区别，需要调整。
你提到的那个问题是因为tag页面也是调用了index.html作为模版来渲染html，忘了考虑这一块，稍后会修复。

**Comment by mtdsj** [comment]
我明白了，谢谢你
