### ISSUE TITLE
Re: Broken image rendering when using under content directory image path.

### ISSUE THREAD

**Issue by hurutoriya** [WingLim/hugo-tania#61]
related Issues: https://github.com/WingLim/hugo-tania/issues/28

@WingLim Hello, nice to meet you.
I love your hugo theme, it is a pretty simple and beautiful design 😄 

Regarding this updates
> With 08a430a, hugo will auto search image in post folder or static folder.

It supported images in post folder but still put the error when I update the `hugo-tania` theme.

```diff
diff --git a/themes/hugo-tania b/themes/hugo-tania
index 0a54b432..99acf147 160000
--- a/themes/hugo-tania
+++ b/themes/hugo-tania
@@ -1 +1 @@
-Subproject commit 0a54b432f9e7318e202760dcd400ab9cefc17882
+Subproject commit 99acf147092a853126c178ffdfaa481ae738d180

```

```bash
Start building sites … 
hugo v0.89.0+extended darwin/amd64 BuildDate=unknown
Error: Error building site: "/Users/hurutoriya/code/hurutoriya.github.io/themes/hugo-tania/layouts/_default/_markup/render-image.html:13:15": execute of template failed: template: _default/_markup/render-image.html:13:15: executing "_default/_markup/render-image.html" at <imageConfig (printf "static/%s" (.Destination | safeURL))>: error calling imageConfig: open /Users/hurutoriya/code/hurutoriya.github.io/static/posts/2017-11-13/images/1.gif: no such file or directory
```
error messages say broken the post directory images rendering images.
 https://github.com/WingLim/hugo-tania/blob/main/layouts/_default/_markup/render-image.html#L13

Actual file structure is here.

I guess  `_markup/render-image.html` build as under `/static` path even under `posts` directory but it seems failed?
Sorry I don't have a knowledge about hugo theme but I would like to share it 🙇 .

https://github.com/hurutoriya/hurutoriya.github.io/tree/source/content/posts/2017-11-13

**Comment by elyserobinson** [comment]
Hopefully you figured it out, but images go in the _static_ folder. I created folders for mine and link to images like for posts: **./about/picofme.jpg**
