### ISSUE TITLE
Dark mode by default?

### ISSUE THREAD

**Issue by OXDBXKXO** [WingLim/hugo-tania#62]
Hi,
I'm trying to make dark mode default but I can't figure it out. I tried using the colorScheme configuration from the `hugo-theme-stack`, but it doesn't seem to work. I tried modifying the source, but I can't get it to work? Is there a way to do it ? If so, maybe a configurable option in the config.yml would be a great adding

**Comment by OXDBXKXO** [comment]
I was able to set dark mode as default with the following modifications:

__assets/ts/colorScheme.ts__
line 8, making currentScheme public
``` js
    public currentScheme: colorScheme;
```
line 61, making setBodyClass() public
``` js
    public setBodyClass() {
```

__assets/ts/features.ts__
Using these new public elements to set dark mode at initialization:
line 10
``` js
const init = () => {
    let cs = new ThemeColorScheme(document.getElementById('dark-mode-button'))
    cs.currentScheme = 'dark';
    cs.setBodyClass();

    if (enableFootnotes) {
        renderFootnotes()
    }
    renderCopyButton()
}
```

I don't know hugo enough to make this an option, but I think it would be a great addition to the project

**Comment by OXDBXKXO** [comment]
Imported the options from __hugo-stack-theme__, made a PR

**Comment by miguno** [comment]
PR is here: https://github.com/WingLim/hugo-tania/pull/65
