### ISSUE TITLE
Change articles route

### ISSUE THREAD

**Issue by CryptoGrogu** [WingLim/hugo-tania#7]
Hi,

Is it possible to change the /articles route to /blog ?
I tried changing the toml and the theme and it doesn't do anything.

**Comment by WingLim** [comment]
See [exampleSite/content/articles.md]()

**Comment by WingLim** [comment]
Sorry for so late to reply.
Create a `blog.md` in directory `content` with the same content as [exampleSite/content/articles.md](https://github.com/WingLim/hugo-tania/blob/main/exampleSite/content/articles.md)
