### ISSUE TITLE
The <em> is not rendeing

### ISSUE THREAD

**Issue by roktcode** [WingLim/hugo-tania#73]
I used em to emphasize text, and it used to show em instead of applying the emphasize. I solved the issue with some help, and it turned out to be in render-heading.html, and the solution was to edit line 9 to be like this `{{ .Text | safeHTML }}`. Hopefuly you will solve it so that it doesn't afeect more users.

**Comment by WingLim** [comment]
Sorry for so late to reply.

Thanks for your feedback, I will fix it soon.
