### ISSUE TITLE
Bug: Math formula didn't take effect in exampleSite

### ISSUE THREAD

**Issue by albinahlback** [WingLim/hugo-tania#8]

**Comment by WingLim** [comment]
Do you mean LaTex？

**Comment by albinahlback** [comment]
Yeah, I mean Katex

**Comment by WingLim** [comment]
Ok, will add it later.

**Comment by WingLim** [comment]
So sorry for that, I forgot I have already support it by using mathjax.
It should be enabled by add `mathjax: true` in article head.
I have add a simple sample in README, take a look.

**Comment by albinahlback** [comment]
Hmm, is it possible to enable Katex instead?

**Comment by WingLim** [comment]
Sure, it's easy, give me a minute.

**Comment by WingLim** [comment]
Now, we support katex.
Take a look at: https://hugo-tania.netlify.app/post/test-katex/

**Comment by albinahlback** [comment]
Thank you! And thank you for the theme as well, it is very nice.

**Comment by WingLim** [comment]
Hope you can use it happily.
If there has any new feature you want to add or bug you want to report, let me know.
