### ISSUE TITLE
Code Copy Button does not work

### ISSUE THREAD

**Issue by Limbend** [WingLim/hugo-tania#81]
There is a button itself, but if you press, then nothing happens. Unlike [your site](https://hugo-tania.netlify.app/post/test-katex/).
I tried with a default config from [config.example.toml](https://github.com/WingLim/hugo-tania/blob/main/exampleSite/config.example.toml) 

I also tried to add a line to the config
enablelinenos = true

Launch method:
```
docker run -it \
  --name="hugo" \
  -p 1313:1313 \
  -v /**my-site**:/src \
  --restart unless-stopped \
klakegg/hugo:ext-debian \
  server --disableFastRender -D
```

**Comment by thomasnotfound** [comment]
I can't reproduce this. It provides expected behavior on https://how.wtf

**Comment by Friedrich42** [comment]
You need to add
```toml
[markup]
[markup.highlight]
  noClasses = false
  lineNos = true
```
to config.toml

example conf https://github.com/Friedrich42/murrr.space/blob/master/config.toml

**Comment by Limbend** [comment]
I used the [standard config.toml](https://github.com/WingLim/hugo-tania/blob/main/exampleSite/config.example.toml) from this topic.
There are the same parameters:
```
[markup]
[markup.highlight]
  noClasses = false
  lineNos = true
```

I did not figure out what the mistake was. But I solved the problem as follows for myself. 
[commit](https://github.com/Limbend/hugo-tania/commit/150e4d30123170e8159b61d3fe8f5548451cfe57)
