### ISSUE TITLE
Add a section to the wiki on how to use custom social icons

### ISSUE THREAD

**Issue by paskn** [WingLim/hugo-tania#85]
You can find the new section here:
https://github.com/paskn/hugo-tania/wiki/Custom

I find this hard to figure out for new hugo users. While some themes have documentation on this, I thought that I can contribute for the theme I really like.

Cheers!

**Comment by WingLim** [comment]
Invitation sended.
You should be able to add this to wiki after you become collaborator.

**Comment by paskn** [comment]
I have added a new section.
