### ISSUE TITLE
Filtering articles by category name does not work

### ISSUE THREAD

**Issue by Friedrich42** [WingLim/hugo-tania#86]
I have a blog here: https://dev.murrr.space/articles/
And it shows that there is 1 article for each category, but when you click on it, site doesn't show any articles.

Source code is open: https://github.com/Friedrich42/murrr.space

**Comment by Friedrich42** [comment]
I suspect that it may be because of categories' names. They have space in them. I had a similar problem in another project (non-hugo)

**Comment by Friedrich42** [comment]
@WingLim I'm willing to contribute if you could point where the problem is and what may be potential fix?

**Comment by WingLim** [comment]
This is not a bug of this theme, you need to enable `json` output to generate data for search plugin.

Add below in your `config.yaml`:
```
outputs:
  home: ["HTML", "RSS", "JSON"]
```

**Comment by fira42073** [comment]
Thank you!
