### ISSUE TITLE
Biography on front page

### ISSUE THREAD

**Issue by albinahlback** [WingLim/hugo-tania#9]
Is it possible to have a small biography on the front page with options for a small text (for example a small text about yourself), a picture, email address and name?

**Comment by WingLim** [comment]
You can add your biography in `_index.md` which is in `exampleSite/content/_index.md`.
It will show on index.
Like:
![image](https://user-images.githubusercontent.com/6434137/119265921-3a1c3c80-bc1b-11eb-9b86-44ed7890c1a0.png)

The email icon is a setting in `config.yaml`, with dfce38b this patch.

```yaml
params:
  socialOptions:
    email: me@example.com
```

**Comment by albinahlback** [comment]
Thanks!
